### ISSUE TITLE
Missing call to serialize unsigned vote cast and merge it with an external signature

### ISSUE THREAD

**Issue by refi93** [input-output-hk/catalyst-core#134]
I'm adding hardware wallet (namely Ledger) support for signing vote casts into our wallet and I can't find these two calls:

* a call to serialize the vote before signing (input expected by the hardware wallet)
* call to combine the unsigned vote cast with the signature returned by the hw wallet to produce the full signed vote

Ledger API for signing vote casts: 

* `signGovernanceVote()` call interface: https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/236b385e8bcafb4ca7cabff5387be2edbcc69771/src/interactions/signGovernanceVote.ts#L18
* integration test cases: https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/27399653ecc227aff2eca827affea66e7651a767/test/integration/__fixtures__/signGovernanceVote.ts#L10

The closest call I found is `sign_vote()` but that one obviously produces the whole signed tx which isn't suitable for this usecase: https://github.com/input-output-hk/catalyst-core/blob/3294fe7a23fe8274af5b03259bf8e9998dbbbb2f/src/chain-wallet-libs/bindings/wallet-core/src/wallet.rs#L140

**Comment by minikin** [comment]
@Mr-Leshiy We'd appreciate your input here, please.

**Comment by Mr-Leshiy** [comment]
Seems to already fixed it with https://github.com/input-output-hk/catalyst-core/pull/169

**Comment by minikin** [comment]
The issue was fixed in #169.
