### ISSUE TITLE
Wallet state management when signing Votes, error when passing other than 8 lanes

### ISSUE THREAD

**Issue by refi93** [input-output-hk/catalyst-core#139]
When signing real votes with the `signVotes()` call (https://github.com/input-output-hk/catalyst-core/blob/340401bb5b1e5bdcf7b01a86cdecf11729ff15bd/src/chain-wallet-libs/bindings/wallet-js/js/index.js#L64), shouldn't the spending counter(s) be in sync with the state of the wallet on the network, and hence somehow passed to the wallet? Currently, they seem to be hardcoded to 1 in the logic constructing the wallet

Also, I see that the wallet [tries to set up 8 lanes](https://github.com/input-output-hk/catalyst-core/blob/340401bb5b1e5bdcf7b01a86cdecf11729ff15bd/src/chain-wallet-libs/bindings/wallet-js/js/index.js#L56), each one with its own spending counter, and if I try to set up just one "lane", I get an `invalid spending counters provided to the set account state function` error. Is this behavior expected? Why are multiple lanes needed at all? Isn't the "basic" use case to have just one lane to sign the votes sequentially?

**Comment by stevenj** [comment]
Correct,  each vote contains its pre-calculated spending counter.  This library should not be managing the spending counter, just using the value it is provided by the dapp/wallet.

There is a Lane field missing from the vote,  I am adding that to the CIP-62 draft for the vote record, and I will discuss this issue with @Mr-Leshiy ASAP.

**Comment by stevenj** [comment]
This should have been resolved, closing,
