### ISSUE TITLE
Serialize also unsigned vote fragment, allow appending external signatures (hw wallets usecase)

### ISSUE THREAD

**Issue by refi93** [input-output-hk/catalyst-core#225]
**Is your feature request related to a problem? Please describe.**
I'm trying to obtain a serialized unsigned vote fragment in order to have it signed by Ledger. So far, I've found just how to serialize a signed vote fragment:

```typescript
  ...
  let tx_builder = builder.build_tx(
    accountId,
    vote.spendingCounter,
    vote.spendingCounterLane
  )
  if (privateKey != undefined) {
    tx_builder = tx_builder.sign_tx(privateKey);
  }
  tx_builder.finalize_tx().to_bytes() // this produces the serialized signed fragment
```
https://github.com/input-output-hk/catalyst-core/blob/f5865be9a9d227e975689e32e6c03b5b34ff5d96/src/chain-wallet-libs/bindings/wallet-wasm-js/js/index.js#L86

However, ledger hw wallet expects a serialized unsigned vote cast as can be seen in its js library integration tests:

https://github.com/vacuumlabs/ledgerjs-cardano-shelley/blob/236b385e8bcafb4ca7cabff5387be2edbcc69771/test/integration/__fixtures__/signGovernanceVote.ts

When I tried to "finalize" an unsigned vote, the call crashed, apparently because the `sign_tx` step wasn't performed

**Describe the solution you'd like**
Add a method to obtain the unsigned vote cast bytes and also a way to append the signature of the vote obtained from the hw wallet

**Comment by minikin** [comment]
@refi93 Thank you for the report.
@Mr-Leshiy Can you help?

**Comment by Mr-Leshiy** [comment]
Understood. Yea, will update it with the described requirements :)

**Comment by minikin** [comment]
@Mr-Leshiy Can we close this issue, or do we still have some things to do?

**Comment by minikin** [comment]
The issue was addressed [here](https://github.com/input-output-hk/catalyst-core/pull/249)
