### ISSUE TITLE
VIT-SS REST api/v0/snapshot/delegator Response Fields

### ISSUE THREAD

**Issue by Ryun1** [input-output-hk/catalyst-core#238]
**Describe the bug**
Incorrect or misleading fields in response from VIT-SS's REST API.

Okay, so see the api doc [here](https://github.com/input-output-hk/catalyst-core/blob/main/book/src/core-vitss-doc/api/v0.yaml).

In the [DelegatorInfo object](https://github.com/input-output-hk/catalyst-core/blob/main/book/src/core-vitss-doc/api/v0.yaml#L1170):
- There is a conflict here between the required section requiring `delegators`, but then in properties there is no `delegators` instead there is `dreps`.
- At first I assumed this is just a simple naming mistake in the `properties` and that `dreps` should just be renamed to `delegators`, two reasons for this:
  - A stake key can delegate to any voting key not just dReps, so IMO it does not make sense to only show delegations to dReps.
  - and this assumption would match the `example` given.
- But looking deeper into VIT's insides I can see this [get_delegator_info function](https://github.com/input-output-hk/catalyst-core/blob/main/src/vit-servicing-station/vit-servicing-station-lib/src/v0/endpoints/snapshot/mod.rs#L116):
  - Reading it's insides it is clear that `dreps` are the main data point and not `delegators` as the API doc would have me believe.

Furthermore, IF this field is only meant to return delegations to dReps only then why is there a field of [`voting_groups` in the API](https://github.com/input-output-hk/catalyst-core/blob/main/book/src/core-vitss-doc/api/v0.yaml#L1175)? If it was only dReps then this field would always return the same value. Thus making it obsolete.

I have tested this on a temporary AWS deployment of VIT from last year and this `drep` field does indeed return voting keys which do not belong to dReps.

My assumption is that the term `dRep` was used as a catch all term to represent any voting key which has received delegations. Then when the docs were written the name was changed to `delegators` to represent that its not just dReps.

**To Reproduce**
Use the /snapshot/delegator endpoint on a VIT deployment.

**Expected behaviour**
This field's name to reflect its values.

**Additional context**
I would have preferred to do a PR myself, but I am unclear what the best solution would be AND I'm unsure if my interpretation of this is correct.

**Comment by minikin** [comment]
@Ryun1 Thank you for the report. Feel free to create a PR. Feel free to let me know if you need any help.

**Comment by stevenj** [comment]
This endpoint has been obsoleted by a new API and service being released.
Closing the issue.
