### ISSUE TITLE
earthly +local fails

### ISSUE THREAD

**Issue by profd2004** [input-output-hk/catalyst-core#523]
**Describe the bug**
earthly +local local command fails.

**Steps to reproduce the behavior:**

1. Clear earthly cash
2. run `earthly +local`
<img width="250" alt="Screenshot 2023-08-17 at 9 58 33 PM" src="https://github.com/input-output-hk/catalyst-core/assets/4429661/129aa5ec-294f-4e2e-b841-5bb6d694adb1">   

**Expected behavior**
earthly +local should complete successfully with out additional host system dependencies outside of docker

**Desktop (please complete the following information):**
Mac OS 14.0
Docker for mac 4.21.1 (114176)

### Additional contexts:

`
./services/voting-node+build |   • Installing watchfiles (0.19.0)
./services/voting-node+build |   • Installing websockets (11.0.3)
        +build-cache |    Compiling multiparty v0.1.0
        +build-cache |    Compiling async-stream-impl v0.3.5
        +build-cache |    Compiling time v0.1.45
        +build-cache |    Compiling scoped-tls v1.0.1
                          Compiling iana-time-zone v0.1.56
        +build-cache |
./services/voting-node+build |   ChefBuildError

./services/voting-node+build |   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
./services/voting-node+build |
./services/voting-node+build |   Building lxml version 4.9.0.
./services/voting-node+build |   <string>:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
./services/voting-node+build |   Building without Cython.
./services/voting-node+build |   Error: Please make sure the libxml2 and libxslt development packages are installed.
./services/voting-node+build |

./services/voting-node+build |   at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
./services/voting-node+build |       143│
./services/voting-node+build |       144│                 error = ChefBuildError("\n\n".join(message_parts))
./services/voting-node+build |       145│
./services/voting-node+build |       146│             if error is not None:
./services/voting-node+build |     → 147│                 raise error from None
./services/voting-node+build |       148│
./services/voting-node+build |       149│             return path
./services/voting-node+build |       150│
./services/voting-node+build |       151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

./services/voting-node+build | Note: This error originates from the build backend, and is likely not a problem with poetry but with lxml (4.9.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "lxml (==4.9.0)"'.

./services/voting-node+build | Warning: The file chosen for install of asgiref 3.7.0 (asgiref-3.7.0-py3-none-any.whl) is yanked. Reason for being yanked: Broken dependencies that cause installation issues
        +build-cache |    Compiling async-stream v0.3.5
./services/voting-node+build | ERROR services/voting-node/Earthfile line 33:4
./services/voting-node+build |       The command
./services/voting-node+build |           RUN poetry install --no-cache --no-root
./services/voting-node+build |       did not complete successfully. Exit code 1
        +build-cache | WARN: Canceled

============================= ❌ FAILURE [Build 🔧] ==============================

Repeating the output of the command that caused the failure
./services/voting-node+build *failed* | --> RUN poetry install --no-cache --no-root
./services/voting-node+build *failed* | Installing dependencies from lock file

./services/voting-node+build *failed* | Package operations: 89 installs, 1 update, 0 removals

./services/voting-node+build *failed* |   • Installing wrapt (1.15.0)
./services/voting-node+build *failed* |   • Installing deprecated (1.2.13)
./services/voting-node+build *failed* |   • Updating setuptools (68.0.0 -> 67.8.0)
./services/voting-node+build *failed* |   • Installing certifi (2023.5.7)
./services/voting-node+build *failed* |   • Installing charset-normalizer (2.1.1)
./services/voting-node+build *failed* |   • Installing idna (3.4)
./services/voting-node+build *failed* |   • Installing opentelemetry-api (1.16.0)
./services/voting-node+build *failed* |   • Installing opentelemetry-semantic-conventions (0.37b0)
./services/voting-node+build *failed* |   • Installing protobuf (4.23.1)
./services/voting-node+build *failed* |   • Installing sniffio (1.3.0)
./services/voting-node+build *failed* |   • Installing typing-extensions (4.7.1)
`
   
<img width="1144" alt="Screenshot 2023-08-17 at 9 38 26 PM" src="https://github.com/input-output-hk/catalyst-core/assets/4429661/c5921bfc-102c-4ccd-85b4-b5b8319bc417">

**Comment by jmgilman** [comment]
[This has apparently been happening for awhile](https://github.com/input-output-hk/catalyst-core/actions/runs/5895759151/job/15992235894#step:5:1198) 😅 I can also reproduce it locally on my machine. It looks like some new deps were added to the final container image but are missing in the build image.

**Comment by profd2004** [comment]
My hero!
