### ISSUE TITLE
No documentation on activevoteplans[i]proposals[i].proposal_id hash 

### ISSUE THREAD

**Issue by profd2004** [input-output-hk/catalyst-core#550]
Observing the hourly snapshot and would like to do generate a heat map or something along those lines to show votes_cast values for proposals. Having trouble going from `d450fba2dae38490595b9bf3f493654dc162669fb8af3c42c5b4a94aa415fd68` for example to proposal title.

Please help! 

Is

<img width="562" alt="Screenshot 2023-09-04 at 9 51 47 AM" src="https://github.com/input-output-hk/catalyst-core/assets/4429661/fb1dd561-67c4-4bb3-9c64-80e25ba3d840">

**Describe the solution you'd like**
Information about how the proposal_id value is derived would be great! 
Didn't see any info in https://github.com/input-output-hk/catalyst-core/tree/main/src/audit nor https://github.com/input-output-hk/catalyst-core/blob/main/src/audit/balance/README.md.

**Comment by profd2004** [comment]
> Hi, you can search for the proposal id in `api/v0/proposals` ,take the `internal_id` field and call `/api/v0/proposals/{internal-id}`

Would you elaborate pretty please? 

This is what I attempted interpreting your response: 
`curl http://127.0.0.1:10000/api/v0/proposals/2ff2fadfb08bd6e800aea7282a58685d8dc5f12c6270a3fab817e0094f30bdff` with internal-id being a value in `activevoteplans[i]proposals[i].proposal_id` 

Also tried running querying just `curl http://127.0.0.1:10000/api/v0/proposals` 

Both of these were against the jormungandr node. Both returned an empty response. 

Should be querying a different api? Is this documented anywhere anyone can point me to?

**Comment by kukkok3** [comment]
The docs for vit servicing station api are [here](https://input-output-hk.github.io/catalyst-core/main/07_web_api/vit-servicing-station-v0.html). I'm not sure what stack are you running locally so I'll refer to the current production environment.
You can` curl https://core.projectcatalyst.io/api/v0/proposals` and you'll get the list of all proposals
You can search for the `proposal_id` in the response to find the proposal you need. If you want only the single proposal take the field `internal_id` from the response and `curl https://core.projectcatalyst.io/api/v0/proposals/{internal_id}`
Ex. proposal_id = 5213228b6f031a6347169d517e1ff3402fff23ca3b83c6096029b5b080edc42e
curl https://core.projectcatalyst.io/api/v0/proposals
Search for 5213228b6f031a6347169d517e1ff3402fff23ca3b83c6096029b5b080edc42e in the response -> internal_id = 0
curl https://core.projectcatalyst.io/api/v0/proposals/0
