### ISSUE TITLE
descending date order for ledger snapshots?

### ISSUE THREAD

**Issue by profd2004** [input-output-hk/catalyst-core#551]
We waste a lot developer's time and computing resources paging through the results just to find and fetch the latest ledger snapshot. 

Is there way to just get the most recent? Or perhaps add a query parameter to order by metadata.timestamp with the newest timestamp first (or just default to it)?

Yes, you can sort the results you get but it's not always guarantee the newest snapshot will be on the initially returned page.

**Comment by jmgilman** [comment]
Hi Darlington,

Thanks for the feedback. This is a known issue and it's actually related to using AWS S3 as a "backend" of sorts. Unfortunately, the S3 API doesn't allow sorting by last modified date, it only supports sorting by lexicographical order. Doing sorting server-side would, of course, defeat the purpose of pagination. 

I have a solution in mind, but I'm also the lead SRE and things tend to get busy around here during the fund 😄 . Hopefully I can get a fix out soon. I'll keep this issue open for tracking purposes.

**Comment by profd2004** [comment]
> Hi Darlington,
> 
> Thanks for the feedback. This is a known issue and it's actually related to using AWS S3 as a "backend" of sorts. Unfortunately, the S3 API doesn't allow sorting by last modified date, it only supports sorting by lexicographical order. Doing sorting server-side would, of course, defeat the purpose of pagination.
> 
> I have a solution in mind, but I'm also the lead SRE and things tend to get busy around here during the fund 😄 . Hopefully I can get a fix out soon. I'll keep this issue open for tracking purposes.

Thanks for the reply and background! Makes sense. 

While a fix is being queue up, we've mirrored the archive in our system and added  it to our rest api with descending timestamp as the default order for anyone else having the same issue: 
https://www.lidonation.com/catalyst-explorer/api#/ledger-snapshots 
<img width="851" alt="Screenshot 2023-09-08 at 5 24 22 PM" src="https://github.com/input-output-hk/catalyst-core/assets/4429661/5ac7a992-b2c9-4293-b995-188d1e229ef3">

**Comment by jmgilman** [comment]
Nice! I have the solution working in our dev cluster. A few things:

1. The `next` field has been removed from the API response
2. Likewise, the associated query parameter has also been removed

Meaning, pagination is gone. The endpoint will return all archives at once. I will deploy it to production here shortly. Thanks for your patience :)

**Comment by jmgilman** [comment]
Changes are live now 😄  Closing this issue.
