### ISSUE TITLE
Provide data to filter proposals by theme in mobile app

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-core#591]
Need to ingest new proposal data from ideascale and expose in vit-ss as discussed here: 
https://input-output.atlassian.net/wiki/spaces/VIT/pages/3977805942/3.10.23+Working+Session

- [x] Update importer config to get new data from ideascale
- [x] Define json structure to insert themes into `proposal.proposal_files_url.themes` field for each proposal (at least 1, no more than 3)
- [x] Implement logic to extract list of **unique** themes; determine whether this should be done inside ideascale importer or github actions
- [x] Define json structure to insert list of unique themes **across all proposals** into the `fund_goals` field (expect as many as 20)
- [x] Test with application to ensure everything working as intended, including checking that cache flushing not impacting by extending how we use fund_goals

feel free to reach @coire1 if you need any help with ideascale.

**Comment by minikin** [comment]
@mike-mcnulty When do we need to have this one?

**Comment by minikin** [comment]
@saibatizoku Can you specify why this task is blocked, please? Probably, creating a blocking issue can be helpful.

**Comment by saibatizoku** [comment]
This ticket is blocked by https://github.com/input-output-hk/fund10-ideascale-importer/issues/6

**Comment by saibatizoku** [comment]
Resuming work.
