### ISSUE TITLE
Log (app_frag_id, jor_frag_id)

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-core#618]
Update logging to capture fragment ID from both jormungandr and the application in order to improve traceability of voting fragments

Should be able to use new app_frag_ID in order to associate fragments logged in sentry vs jormungandr

To generate app_frag_ID should use same calculation used by the app. 
Q: does this come from chain_wallet_libs?

**Comment by minikin** [comment]
@jmgilman

**Comment by Mr-Leshiy** [comment]
related to https://github.com/input-output-hk/catalyst-sre-incidents/issues/12
