### ISSUE TITLE
Update ideascale proposal submission form with themes in alignment with sandbox data structure

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-core#620]
Need to make sure that the proposal submission form is updated in Ideascale to reflect the changes made to the ideascale importer / mobile app to support the new Themes Filter feature. Data structure in the submission form needs to agree with how data is structured in sandbox for dev purposes prior to changing actual submission form. 

- [x] Update proposal submission form in ideascale
- [x] Update f10 ideascale script https://github.com/input-output-hk/fund10-ideascale-importer/pull/11
- [x] Perform dry run using prod-like data to validate new feature end to end

**Comment by coire1** [comment]
Proposal form is updated in Ideascale Sandbox (relevant keys will be replicated in prod).
It should be the final one but it is not signed off yet.
Here is the list of the fields (marked with an asterisk the ones relevant for the app):

```
f11_name_of_main_applicant
f11_individual_or_entity
f11_additional_applicants
f11_technical_sub_contracting
*f11_requested_funds
f11_proposal_duration
f11_auto_translated
*f11_proposal_solution
*f11_link_1
*f11_link_2
*f11_link_3
f11_dependency
f11_dependency_details
*f11_open_source_choice
f11_open_source
*f11_themes
f11_sdg_rating
f11_proposed_solution
f11_positive_impact
f11_capability_to_deliver
f11_milestone_1
f11_milestone_2
f11_milestone_3
f11_milestone_4
f11_milestone_5
f11_final_milestone
*f11_project_team
f11_value_for_money
f11_budget_breakdown
f11_terms_and_conditions
```
The campaign ids used in the sandbox are: `395, 400, 399, 401, 402, 403`
The stage ids used in the sandbox are: `4573, 4574, 4575, 4576, 4577`

**Comment by mike-mcnulty** [comment]
thanks @coire1. looks like all field names are fund specific. do these get mapped to standard backend field names during the import process, or will all these fields need to be updated in the app? want to be clear on any enabling work on either importer, backend, or app side to consume fields without issue

as far as specific fields, a few questions:
- has "problem statement" been removed entirely from the form? not seeing it anywhere
- confirming that "*f11_proposal_solution" will be character limited as in the past? i see there is also "f11_proposed_solution" - can you explain the difference?
- "*f11_project_team" is this the same field that was agreed on in F10 for the "relevant experience" field shown in the app?

cc: @kukkok3

**Comment by coire1** [comment]
These field names are in Ideascale and can be configured in the various importer tools to properly populated the backend.
No changes are needed in the voting app (we switched already field names without any direct impact in the app in F10).

These is the list of the **custom fields**. Some other fields are static and never change as we don't have such capability (such as the title, authors, etc. ).

-  "problem statement" is not part of the custom fields, but it's the main content of the proposal in Ideascale. It's the default `text` field in Ideascale responses. It's the same config as per F10. It will be limited to 200 chars.
- `*f11_proposal_solution` is limited to 200 chars. `f11_proposed_solution` it's the field for the extended description of the solution that will not appear in the app.
- `*f11_project_team`, yes it's the same field we previously used for the relevant experience. It will not be limited in length (as in F10)

**Comment by kukkok3** [comment]
@coire1 There are still some problems with ideascale sanbox, I left few comments here https://input-output.atlassian.net/browse/NPG-8469

**Comment by coire1** [comment]
@kukkok3 Addressed the problems described in the JIRA ticket.

**Comment by kukkok3** [comment]
@coire1 the ideascale changes will be part of another PR. @saibatizoku is working on that. This PR is only to get the continuous snapshot going
