### ISSUE TITLE
Update fund winners script given removal of downvoting

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-core#621]
Fund11 voting will not have any downvoting. All challenges will have options "Yes" and "Abstain", and the winner will be determined based on the highest number of "Yes" votes only. 

This change mimics the voting setup for the "Fund Operations" challenge in Fund10 - applying that setup across the entire voting event. 

![Image](https://github.com/input-output-hk/catalyst-core/assets/91077234/ab9ba912-021d-4680-be98-c67662c2928f)
src: https://docs.projectcatalyst.io/catalyst-basics/fund10/fund10-parameters

- [ ] Update fund winners script to reflect changes
- [ ] Test changes against Fund10 data

**Comment by Mr-Leshiy** [comment]
I have checked `catalyst-toolbox` voter rewards cli tool, seems it does not need to update it at all. 
Because as an input it takes just a vote counts for each user in the following format:
```
{
"7a88143c953564f2b7668bf10903edca976b0af2c4aa80c1e87aa3e41f92c7a1":18,
"b1eb8f3cb8a5e05cbfd37e78e47ecfa0e94395e0bf5f275e543c55d11ecd1538":4,
}
```
So right now looking how this data is generated and will it properly counts votes :)

**Comment by Mr-Leshiy** [comment]
For voter rewards script no need to update, it will work properly due to our requirements.
Even if we want to apply threshold of vote counts it is already implemented and script has the corresponding argument.

**Comment by Mr-Leshiy** [comment]
Proposer rewards script also is fine and no need to update.
