### ISSUE TITLE
Sanity test latest wallet versions and update supported wallets gitbook 

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-core#622]
Sanity check voting registration for cardano wallets
For each wallet listed

1. Restore a mainnet wallet using the wallet UI 
2. Register for voting using the wallet UI
3. Check the registration metadata shown by the wallet UI are structred correctly
4. Take a snapshot using the snapshot tool and check the registration transaction has been picked up
5. Check the qr code is correct using jcli to estract the voting key and use the voting power tool/ mobile application as well to check the qrcode works as intended

[List of supported wallets and a guide on how to register](https://docs.projectcatalyst.io/about-project-catalyst/what-is-project-catalyst)
[Registration metadata format](https://cips.cardano.org/cips/cip36/#registrationmetadataformat) 

At the end of the test in [gitbook](https://docs.projectcatalyst.io/catalyst-basics/how-to-register-as-a-voter/wallet-registration-guide/supported-wallets), update "last updated" date and "version" column with latest tested versions

Tested | Wallet | Version | Result 
- [x] | [Adalite](https://adalite.io/) | 6.11.17 | ✔️
- [x] | [Adalite](https://adalite.io/) + Ledger S/X | 6.11.17 + 2.73.0 |  ✔️
- [x] | [Adalite](https://adalite.io/) + Trezor T | 6.11.17 + 2.6.3 | ✔️
- [x] | [Daedalus](https://daedaluswallet.io/en/download/) | 5.3.0 | ✔️
- [x] | [Daedalus](https://daedaluswallet.io/en/download/) + Ledger S/X | 5.3.0 + 2.73 | ✔️
- [x] | [Daedalus](https://daedaluswallet.io/en/download/) + Trezor T | 5.3.0 + 2.6.3 | ✔️
- [x] | [Yoroi ](https://yoroi-wallet.com/#/) [Chrome] | 5.0.0 | ✔️
- [x] | [Yoroi ](https://yoroi-wallet.com/#/) [Android] | 4.23 | ✔️
- [x] | [Yoroi ](https://yoroi-wallet.com/#/) [Chrome] + Ledger S/X | 5.0.0 + 2.73 | ✔️
- [x] | [Yoroi ](https://yoroi-wallet.com/#/) [Chrome] + Trezor T | 5.0.0 + 2.6.3 | ✔️
- [x] | [Typhon ](https://typhonwallet.io/) [Chrome]  | 3.0.18 -> registration still closed :x:
- [x] | [Eternl](https://eternl.io/) [Chrome] | 1.11.16 | ✔️
- [x] | [Eternl](https://eternl.io/) [Chrome] + Ledger S/X | 1.11.16 + 2.73 | ✔️
- [x] | [Eternl](https://eternl.io/) [Chrome] + Trezor T | 1.11.16 + 2.6.3 | ✔️
- [x] | [Eternl](https://eternl.io/) [Android] | 1.11.16 | ✔️
- [x] #644

**Comment by kukkok3** [comment]
Tested so far:

- [ ] Adalite 6.11.17 OK
- [ ] Typhon[Chrome] 3.0.18 -> registration still closed
- [ ] Yoroi[Chrome] 4.23.200 -> does not give you the qr-code
- [ ]  Etrnal[Chrome]
