### ISSUE TITLE
Implement new TTL logic in mobile app

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-core#637]
As an app user, I need every vote that I cast to be confirmed & counted on the backend. 

Background:
Current application logic sets TTL for voting fragment based on current network congestion. This logic can be found here: https://github.com/input-output-hk/norns/blob/develop-fund11/src/utils/helpers.js#L278

Hypothesis that this is leading to high rate of rejections during periods of high traffic.

Tasks:
- [ ] Assess current application logic, in light of findings from investigation of lost fragments on backend side
- [ ] Define ideal TTL to be set on all votes cast by the app, regardless of current network traffic
- [ ] Implement new logic in the application

cc: @stevenj @cong-or @coire1

**Comment by Mr-Leshiy** [comment]
Won't do it
