### ISSUE TITLE
Add event data for prod

### ISSUE THREAD

**Issue by jmgilman** [input-output-hk/catalyst-core#639]
The [prod folder](https://github.com/input-output-hk/catalyst-core/tree/main/src/event-db/stage_data/prod) is empty. In order to configure the voting node so that it starts taking snapshots, the event data needs to be configured correctly, as we've done with other environments. I recommend using the fund11 dates so that snapshots start and stop at the appropriate time.

**Comment by kukkok3** [comment]
Also need to remember to take snapshots only for mainnet and to set the url to prod cat data service as default in the application
