### ISSUE TITLE
Automate Eternl wallet registration

### ISSUE THREAD

**Issue by kukkok3** [input-output-hk/catalyst-core#679]
Create a pregenerated preprod wallet keys in the repo
Automate using playwright

Open the preprod wallet on [Eternl](https://eternl.io/)
Check that the pregenerated wallet still holds enough funds to register
Register for voting on the Eternl wallet UI using the wallets
Check that the registration is successful
Note: create a new set of wallet keys specifically for Eternl

https://docs.projectcatalyst.io/project-catalyst-testnet/testnet-voting-events/testnet-user-guide/register-wallet

to get test ada -> https://docs.cardano.org/cardano-testnet/tools/faucet/

**Comment by Mr-Leshiy** [comment]
Not relevant anymore
