### ISSUE TITLE
voting-tool-rs: database test data not publicly accessible

### ISSUE THREAD

**Issue by CatalystReviewer11** [input-output-hk/catalyst-core#695]
https://github.com/input-output-hk/catalyst-core/blob/b05c57d72d0ad36aecb2e0bd0480f519d1d85081/src/voting-tools-rs/README.md?plain=1#L21

> Database tests perform predefined queries against a test database. If the results don't match the snapshots, the test fails. This requires having the correct data in your database. The current test data can be found [here](https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/index.html#13/).

The URI above (https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/index.html) gives a HTTP 403 error page:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>MSBM423Z8XC9VRPT</RequestId>
<HostId>7W6lpJjghJrxvYgPUGeAQPxlup790E7BkOKikasqcw0rWsGosEOuCj9tKsNCSSYRqXTNOdHxLm0=</HostId>
</Error>
```

**Comment by Mr-Leshiy** [comment]
@CatalystReviewer11 thank you for your issue !
We have updated this readme with this PR https://github.com/input-output-hk/catalyst-core/pull/696, that Readme was stale and not updated for a long time.
Unfortunately there is no testnet publicly available `cardano-db-sync` instance.
And for security response we can't expose that one which we are using internally.
So the only option is to spin up a `cardano-db-sync` locally following guides from this repo https://github.com/IntersectMBO/cardano-db-sync.
